//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.10.08 at 02:50:33 PM CEST
//

@javax.xml.bind.annotation.XmlSchema(
    namespace = "urn:oasis:names:tc:opendocument:xmlns:container",
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package tech.mathieu.epub.container;
