//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.10.08 at 03:07:05 PM CEST
//


package tech.mathieu.epub.opf.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "creator")
public class Creator {

  @XmlValue
  private String value;

  @XmlAttribute(name = "id")
  private String id;

  @XmlAttribute(name = "role", namespace = "http://www.idpf.org/2007/opf")
  private String role;
  @XmlAttribute(name = "file-as", namespace = "http://www.idpf.org/2007/opf")
  private String fileAs;


  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  public String getRole() {
    return role;
  }


  public void setRole(String value) {
    this.role = value;
  }


  public String getFileAs() {
    return fileAs;
  }


  public void setFileAs(String value) {
    this.fileAs = value;
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }
}
