//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.10.08 at 03:07:05 PM CEST
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://purl.org/dc/elements/1.1/")
package tech.mathieu.epub.opf.metadata;
