CREATE TABLE COLLECTION (
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(4000),
    TYPE       VARCHAR(4000),
    COVER_PATH VARCHAR(4000)
);

ALTER TABLE BOOK
    ADD FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION(ID);
