CREATE TABLE EBOOK_USER(
    ID          BIGINT PRIMARY KEY NOT NULL,
    NAME        VARCHAR(4000) NOT NULL,
    PASSWORD    VARCHAR(4000) NOT NULL,
    ROLES       VARCHAR(4000) NOT NULL
);

CREATE UNIQUE INDEX user_name
ON EBOOK_USER(NAME);
