ALTER TABLE BOOK
    ADD COLUMN COVER_PATH VARCHAR(4000),
    ADD COLUMN BOOK_PATH VARCHAR(4000);

UPDATE BOOK set
COVER_PATH = CONCAT(PATH, '/cover.jpeg'),
BOOK_PATH = CONCAT(PATH, '/orginal.epub');

ALTER TABLE BOOK DROP COLUMN PATH;