CREATE TABLE COLLECTION (
    ID         INTEGER PRIMARY KEY,
    NAME       VARCHAR(4000),
    TYPE       VARCHAR(4000),
    COVER_PATH VARCHAR(4000)
);

ALTER TABLE BOOK
    ADD COLUMN COLLECTION_ID  INTEGER,
    ADD COLUMN GROUP_POSITION INTEGER;

ALTER TABLE BOOK
    ADD FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION(ID);
